set guioptions=cMg    " do not show menu and toolbar
set lines=50 columns=96
set vb t_vb=          " disable any beeps or flashes on error
set mouse=a           " enable mouse in GUI mode
set background=dark
set cursorline
set guifont=DejaVu\ Sans\ Mono\ 9
colorscheme railscasts
