#
# Executes commands at login pre-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

if [[ -f "$HOME/.rbenvrc" ]]; then
  source "$HOME/.rbenvrc"
fi

if [[ -f "$HOME/.phpenvrc" ]]; then
  source "$HOME/.phpenvrc"
fi
